language: php
php:
  - '5.6'
  - '7.0'

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - composer global require friendsofphp/php-cs-fixer
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover coverage.clover
  - php-cs-fixer --diff --dry-run -v fix .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover