language: php
php:
  - '5.6'
  - '7.0'

before_script:
  - composer global require friendsofphp/php-cs-fixer
  - composer install

script:
  - ./vendor/bin/phpunit
  - php php-cs-fixer --diff --dry-run -v fix .