language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer install

script:
  - vendor/bin/php-cs-fixer fix -v —dry-run
  - phpunit —coverage-clover build/logs/clover.xml